root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  exclude_dir = ["assets"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  delay = 1000 # Compila el proyecto después de 1000ms desde el último cambio detectado
  stop_on_error = true
  send_interrupt = false
  kill_delay = "0s"

[log]
  time = true
  level = "debug"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = false
